Repository ibnaleem/gosearch, pull requests merged in 2025-01, with the labels that each got.

#18 Add 100 websites
  data.json
  tests/test.go
Labels: enhancement

#20 Refactor and enhance the main file
  go.mod
  go.sum
  gosearch.go
Labels: enhancement

#23 Add more email domains to the list
  data.json
  gosearch.go
Labels: enhancement

#32 Fix false positives for figma.com
  data.json
Labels: false positive

#33 Fix false positives for codechef.com
  data.json
Labels: false positive

#36 Fix possible race conditions during search
  gosearch.go
Labels: enhancement, bug fix

#40 Fix false positives for twitch.tv
  data.json
Labels: false positive, bug fix

#41 Fix false positives for cracked.com
  data.json
Labels: false positive, bug fix

#42 feat(data): add sourcehut
  data.json
Labels: enhancement

#43 Url Probe Fix
  gosearch.go
Labels: bug fix

#45 Remove old user summary file
  gosearch.go
Labels: enhancement, bug fix

#46 Search for Usernames on BreachDirectory instead of Emails
  go.mod
  gosearch.go
Labels: enhancement

#47 Refactor and format `gosearch.go`
  gosearch.go
Labels: enhancement

#48 fix: print errors instead of using `fmt.Errorf`
  gosearch.go
Labels: bug fix

#49 build(deps): upgrade `gobreach`
  go.mod
  go.sum
  gosearch.go
Labels: bug fix, dependencies

#53 Fix false false positives for `app.daily.dev`
  data.json
Labels: false positive, bug fix

#54 perf: Replace encoding/json with Sonic for accelerated JSON unmarshalling
  go.mod
  go.sum
  gosearch.go
Labels: enhancement

#55 feat(config): add custom UserAgent support with RFC 1945 compliance
  gosearch.go
Labels: enhancement

#56 fix: avoid changing global User-Agent variable
  gosearch.go
Labels: enhancement, bug fix
